# Generated by Django 2.1.7 on 2019-03-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20190319_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='have_read',
            new_name='have',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='send_to',
            new_name='sendto',
        ),
    ]
