# Generated by Django 2.2 on 2019-04-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='paint',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
