# Generated by Django 2.2 on 2019-04-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_paint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='paint',
        ),
    ]
