# Generated by Django 2.1.7 on 2019-03-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_post_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmark',
        ),
    ]
