# Generated by Django 2.1.7 on 2019-03-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_remove_post_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='thread',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
