# Generated by Django 2.1.7 on 2019-03-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_auto_20190316_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='key',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
