# Generated by Django 2.1.7 on 2019-03-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_remove_post_bookmark'),
        ('users', '0004_auto_20190315_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmark',
            field=models.ManyToManyField(related_name='bookmarks', to='threads.Post'),
        ),
    ]
