version: '2'  

services:  
  nginx:
    image: nginx:1.13
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "8000:8000"
    volumes:
      - ../site:/site
      - ../assets:/assets
      - ../config/dev/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 8000
    extra_hosts:
      - "waitress:${ADDRESS}"

  postgres:
      image: postgres:9.6
      container_name: ${COMPOSE_PROJECT_NAME}_postgres
      volumes:
        - db:/var/lib/postgresql/data
        - ./db/:/db/
      ports: 
        - "5432:5432"
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASS}
        - POSTGRES_DB=${DB_NAME}

volumes:
    db:
        driver: local